[workspace]
authors = ["Philip Reese <philipreese@mail.com>"]
channels = ["conda-forge"]
name = "the-record"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"

[pypi-dependencies]
pylast = ">=7.0.2, <8"
python-dotenv = ">=1.2.2, <2"
