/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Stats
         * @description Retrieve high-level listening history metrics.
         */
        get: operations["read_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/top-artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Top Artists
         * @description Retrieve top artists for a specified time range.
         */
        get: operations["read_top_artists_api_top_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/top-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Top Tracks
         * @description Retrieve top tracks for a specified time range.
         */
        get: operations["read_top_tracks_api_top_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Heatmap
         * @description Retrieve daily play counts for a calendar heatmap visualization.
         */
        get: operations["read_heatmap_api_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Hourly Trends
         * @description Retrieve play counts grouped by the hour of the day.
         */
        get: operations["read_hourly_trends_api_trends_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/punchcard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Punchcard
         * @description Retrieve play counts grouped by day-of-week and hour (keys: '{dow}_{HH}', dow 0=Sun).
         */
        get: operations["read_punchcard_api_trends_punchcard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Monthly Trends
         * @description Retrieve play counts grouped by month (chronological).
         */
        get: operations["read_monthly_trends_api_trends_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Streak
         * @description Retrieve active and historical daily listening streaks.
         */
        get: operations["read_streak_api_trends_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wrapped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Wrapped
         * @description Retrieve aggregated review stats for custom time intervals (Spotify Wrapped style).
         */
        get: operations["read_wrapped_api_wrapped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Recent
         * @description Retrieve recent listens in reverse-chronological order with cursor-based pagination.
         */
        get: operations["read_recent_api_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Track Stats
         * @description Retrieve all-time play count (and duration when available) for a specific track.
         */
        get: operations["read_track_stats_api_track_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playing-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Playing Now
         * @description Fetch the currently playing track from ListenBrainz, or the most recent listen if nothing is playing.
         */
        get: operations["get_playing_now_api_playing_now_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/last-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Last Played
         * @description Return the most recent listen from the local DB with no LB network call — fast cold-start pre-population.
         */
        get: operations["get_last_played_api_last_played_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Sync
         * @description Kick off a background sync with ListenBrainz and return immediately.
         *     Poll GET /api/sync/status for progress and results.
         */
        post: operations["start_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Status
         * @description Return the current state of the background sync job.
         */
        get: operations["get_sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/on-this-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read On This Day
         * @description Retrieve listens for today's calendar date grouped by prior year.
         */
        get: operations["read_on_this_day_api_on_this_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistInfo */
        ArtistInfo: {
            /** Artist */
            artist: string;
            /** Play Count */
            play_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LastPlayedEntry */
        LastPlayedEntry: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Unix Ts */
            unix_ts: number;
            /** Cover Art Url */
            cover_art_url?: string | null;
        };
        /** ListenEntry */
        ListenEntry: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Unix Ts */
            unix_ts: number;
            /** Source */
            source: string;
        };
        /** MonthlyTrendInfo */
        MonthlyTrendInfo: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /** OnThisDayGroup */
        OnThisDayGroup: {
            /** Year */
            year: number;
            /** Listens */
            listens: components["schemas"]["ListenEntry"][];
        };
        /** PlayingNowResponse */
        PlayingNowResponse: {
            /** Is Playing */
            is_playing: boolean;
            /** Artist */
            artist?: string | null;
            /** Title */
            title?: string | null;
            /** Release */
            release?: string | null;
            /** Cover Art Url */
            cover_art_url?: string | null;
            last_played?: components["schemas"]["LastPlayedEntry"] | null;
        };
        /** StatsSummaryResponse */
        StatsSummaryResponse: {
            /** Total Listens */
            total_listens: number;
            /** Unique Artists */
            unique_artists: number;
            /** Unique Tracks */
            unique_tracks: number;
            /** Days Active */
            days_active: number;
            /** Avg Per Day */
            avg_per_day: number;
            /** Top Source */
            top_source: string;
            /** Db Type */
            db_type?: string | null;
            /** First Year */
            first_year?: number | null;
        };
        /** StreakStatsResponse */
        StreakStatsResponse: {
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
        };
        /** SyncStartResponse */
        SyncStartResponse: {
            /** Status */
            status: string;
            /** Mode */
            mode?: string | null;
            /** Message */
            message?: string | null;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Running */
            running: boolean;
            /** Finished */
            finished: boolean;
            /** Mode */
            mode: string;
            /** Batches Fetched */
            batches_fetched: number;
            /** Synced Count */
            synced_count: number;
            /** Lb Total */
            lb_total: number;
            /** Local Total */
            local_total: number;
            /** Error */
            error?: string | null;
        };
        /** TrackInfo */
        TrackInfo: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Play Count */
            play_count: number;
        };
        /** TrackStatsResponse */
        TrackStatsResponse: {
            /** Play Count */
            play_count: number;
            /** Duration Secs */
            duration_secs?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WrappedArtist */
        WrappedArtist: {
            /** Name */
            name: string;
            /** Plays */
            plays: number;
        };
        /** WrappedDataResponse */
        WrappedDataResponse: {
            /** Total Plays */
            total_plays: number;
            top_artist?: components["schemas"]["WrappedArtist"] | null;
            top_track?: components["schemas"]["WrappedTrack"] | null;
            peak_day?: components["schemas"]["WrappedPeakDay"] | null;
            /** Minutes Listened */
            minutes_listened: number;
        };
        /** WrappedPeakDay */
        WrappedPeakDay: {
            /** Date */
            date: string;
            /** Plays */
            plays: number;
        };
        /** WrappedTrack */
        WrappedTrack: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Plays */
            plays: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummaryResponse"];
                };
            };
        };
    };
    read_top_artists_api_top_artists_get: {
        parameters: {
            query?: {
                /** @description Time range in days: 30, 90, 365, or 'all' */
                range?: "30" | "90" | "365" | "all";
                /** @description Max results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_top_tracks_api_top_tracks_get: {
        parameters: {
            query?: {
                /** @description Time range in days: 30, 90, 365, or 'all' */
                range?: "30" | "90" | "365" | "all";
                /** @description Max results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_heatmap_api_heatmap_get: {
        parameters: {
            query?: {
                /** @description The calendar year to display */
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_hourly_trends_api_trends_hourly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    read_punchcard_api_trends_punchcard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    read_monthly_trends_api_trends_monthly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyTrendInfo"][];
                };
            };
        };
    };
    read_streak_api_trends_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakStatsResponse"];
                };
            };
        };
    };
    read_wrapped_api_wrapped_get: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2025) */
                year?: number | null;
                /** @description Filter by quarter: Q1, Q2, Q3, Q4 */
                quarter?: ("Q1" | "Q2" | "Q3" | "Q4") | null;
                /** @description Filter by month: M1 to M12 */
                month?: ("M1" | "M2" | "M3" | "M4" | "M5" | "M6" | "M7" | "M8" | "M9" | "M10" | "M11" | "M12") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WrappedDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_recent_api_recent_get: {
        parameters: {
            query?: {
                /** @description Max results per page (1–100) */
                limit?: number;
                /** @description Cursor: unix_ts of the last item from the previous page */
                before_ts?: number | null;
                /** @description Cursor: id of the last item from the previous page */
                before_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_track_stats_api_track_stats_get: {
        parameters: {
            query: {
                /** @description Artist name */
                artist: string;
                /** @description Track title */
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playing_now_api_playing_now_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayingNowResponse"];
                };
            };
        };
    };
    get_last_played_api_last_played_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayingNowResponse"];
                };
            };
        };
    };
    start_sync_api_sync_post: {
        parameters: {
            query?: {
                /** @description Sync mode: 'normal' or 'full' */
                mode?: "normal" | "full";
            };
            header?: {
                "x-sync-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    read_on_this_day_api_on_this_day_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnThisDayGroup"][];
                };
            };
        };
    };
}
