/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Stats
         * @description Retrieve high-level listening history metrics.
         */
        get: operations["read_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/top-artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Top Artists
         * @description Retrieve top artists for a specified time range.
         */
        get: operations["read_top_artists_api_top_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/top-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Top Tracks
         * @description Retrieve top tracks for a specified time range.
         */
        get: operations["read_top_tracks_api_top_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Heatmap
         * @description Retrieve daily play counts for a calendar heatmap visualization.
         */
        get: operations["read_heatmap_api_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/hourly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Hourly Trends
         * @description Retrieve play counts grouped by the hour of the day.
         */
        get: operations["read_hourly_trends_api_trends_hourly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/punchcard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Punchcard
         * @description Retrieve play counts grouped by day-of-week and hour (keys: '{dow}_{HH}', dow 0=Sun).
         */
        get: operations["read_punchcard_api_trends_punchcard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Monthly Trends
         * @description Retrieve play counts grouped by month (chronological).
         */
        get: operations["read_monthly_trends_api_trends_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Streak
         * @description Retrieve active and historical daily listening streaks.
         */
        get: operations["read_streak_api_trends_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Narrative
         * @description Retrieve dynamic narrative strings for the UI.
         */
        get: operations["read_narrative_api_narrative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wrapped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Wrapped
         * @description Retrieve aggregated review stats for custom time intervals (Spotify Wrapped style).
         */
        get: operations["read_wrapped_api_wrapped_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Recent
         * @description Retrieve recent listens in reverse-chronological order with cursor-based pagination.
         */
        get: operations["read_recent_api_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Track Stats
         * @description Retrieve all-time play count (and duration when available) for a specific track.
         */
        get: operations["read_track_stats_api_track_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/track-stats/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read Track Stats Batch
         * @description Retrieve all-time play count and first available non-null duration for a list of tracks.
         */
        post: operations["read_track_stats_batch_api_track_stats_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover-art": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Cover Art
         * @description Return cached cover art URLs and schedule background resolution for misses.
         */
        post: operations["get_cover_art_api_cover_art_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playing-now": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Playing Now
         * @description Fetch the currently playing track from ListenBrainz, or the most recent listen if nothing is playing.
         */
        get: operations["get_playing_now_api_playing_now_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/last-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Last Played
         * @description Return the most recent listen from the local DB with no LB network call — fast cold-start pre-population.
         */
        get: operations["get_last_played_api_last_played_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Sync
         * @description Kick off a background sync with ListenBrainz and return immediately.
         *     Poll GET /api/sync/status for progress and results.
         */
        post: operations["start_sync_api_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Status
         * @description Return the current state of the background sync job.
         */
        get: operations["get_sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/on-this-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read On This Day
         * @description Retrieve listens for today's calendar date grouped by prior year.
         */
        get: operations["read_on_this_day_api_on_this_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Listens
         * @description Export listening history as CSV or JSON download.
         */
        get: operations["export_listens_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/day/{date_str}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Day Listens
         * @description Retrieve all listens for a specific calendar date, in chronological order.
         */
        get: operations["read_day_listens_api_day__date_str__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/monthly/{year}/{month}/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Monthly Weekly Breakdown
         * @description Retrieve play counts grouped by week-of-month for a given year and month.
         */
        get: operations["read_monthly_weekly_breakdown_api_trends_monthly__year___month__weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/top-artist-trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Top Artist Trends
         * @description Retrieve top N artists with their monthly breakdowns for a specified year.
         */
        get: operations["read_top_artist_trends_api_top_artist_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artist-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Artist Trend
         * @description Retrieve top N tracks of an artist with their monthly breakdowns for a specified year.
         */
        get: operations["read_artist_trend_api_artist_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artist/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Artist Stats
         * @description Retrieve comprehensive personal listening stats for a specific artist.
         */
        get: operations["read_artist_stats_api_artist_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listens/{listen_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Listen
         * @description Fetch a single listen with its effective (corrected) values and correction metadata.
         */
        get: operations["get_listen_api_listens__listen_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Listen
         * @description Permanently delete a listen and any per-listen correction from the local DB.
         */
        delete: operations["delete_listen_api_listens__listen_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listens/{listen_id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Listen
         * @description Persist a per-listen metadata correction and write back to ListenBrainz.
         */
        post: operations["correct_listen_api_listens__listen_id__correction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listens/{listen_id}/correction/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Listen Correction
         * @description Remove the per-listen correction, reverting to track correction or raw values.
         */
        post: operations["revert_listen_correction_api_listens__listen_id__correction_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Correct Track
         * @description Apply corrections to all listens of a logical track (canonical track correction).
         */
        post: operations["correct_track_api_tracks_correction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/correction/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Track Correction
         * @description Remove a canonical track correction, reverting all matching listens to raw values.
         */
        post: operations["revert_track_correction_api_tracks_correction_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Musicbrainz
         * @description Proxy MusicBrainz recording search, rate-limited to one request at a time.
         */
        get: operations["search_musicbrainz_api_mb_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cover-art/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Cover Art
         * @description Return MB releases with CAA cover art URLs for a given artist+album or recording MBID.
         */
        get: operations["search_cover_art_api_cover_art_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playing-now/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Playing Now Stream
         * @description SSE stream that pushes playing-now state every 15 s.
         */
        get: operations["playing_now_stream_api_playing_now_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle Http Get */
        get: operations["handle_http_get_api_graphql_get"];
        put?: never;
        /** Handle Http Post */
        post: operations["handle_http_post_api_graphql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistAnniversary */
        ArtistAnniversary: {
            /** Artist */
            artist: string;
            /** First Listen Ts */
            first_listen_ts: number;
            /** Years */
            years: number;
            /** Total Plays */
            total_plays: number;
        };
        /** ArtistInfo */
        ArtistInfo: {
            /** Artist */
            artist: string;
            /** Play Count */
            play_count: number;
            /** Rank */
            rank?: number | null;
        };
        /** ArtistMonthlyTrend */
        ArtistMonthlyTrend: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /** ArtistStatsResponse */
        ArtistStatsResponse: {
            /** Artist */
            artist: string;
            /** Total Plays */
            total_plays: number;
            /** Rank */
            rank?: number | null;
            /** Top Tracks */
            top_tracks: components["schemas"]["ArtistTopTrack"][];
            /** Monthly Trends */
            monthly_trends: components["schemas"]["ArtistMonthlyTrend"][];
            peak_day?: components["schemas"]["WrappedPeakDay"] | null;
            /** Hourly */
            hourly: {
                [key: string]: number;
            };
            /** First Listen Ts */
            first_listen_ts?: number | null;
            /** Plays Since Discovery */
            plays_since_discovery?: number | null;
        };
        /** ArtistTopTrack */
        ArtistTopTrack: {
            /** Title */
            title: string;
            /** Play Count */
            play_count: number;
            /** First Listen Ts */
            first_listen_ts?: number | null;
            /** Last Listen Ts */
            last_listen_ts?: number | null;
            /** Album */
            album?: string | null;
            /** Duration Secs */
            duration_secs?: number | null;
            /** Representative Listen Id */
            representative_listen_id?: number | null;
        };
        /** ArtistTrendResponse */
        ArtistTrendResponse: {
            /** Artist */
            artist: string;
            /** Year */
            year: number;
            /** Trends */
            trends: components["schemas"]["TrackTrendSeries"][];
        };
        /** ArtistTrendSeries */
        ArtistTrendSeries: {
            /** Artist */
            artist: string;
            /** Play Count */
            play_count: number;
            /** Monthly Counts */
            monthly_counts: components["schemas"]["ArtistMonthlyTrend"][];
        };
        /** CoverArtResult */
        CoverArtResult: {
            /** Release Mbid */
            release_mbid: string;
            /** Release Title */
            release_title: string;
            /** Artist Credit */
            artist_credit: string;
            /** Date */
            date?: string | null;
        };
        /** CoverArtSearchResponse */
        CoverArtSearchResponse: {
            /** Results */
            results: components["schemas"]["CoverArtResult"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LastPlayedEntry */
        LastPlayedEntry: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Unix Ts */
            unix_ts: number;
            /** Cover Art Url */
            cover_art_url?: string | null;
        };
        /** ListenCorrectionRequest */
        ListenCorrectionRequest: {
            /** Artist */
            artist?: string | null;
            /** Title */
            title?: string | null;
            /** Album */
            album?: string | null;
            /** Duration Secs */
            duration_secs?: number | null;
            /** Recording Mbid */
            recording_mbid?: string | null;
            /** Cover Art Url */
            cover_art_url?: string | null;
        };
        /** ListenEntry */
        ListenEntry: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Unix Ts */
            unix_ts: number;
            /** Source */
            source: string;
            /** Duration Secs */
            duration_secs?: number | null;
            /** Album */
            album?: string | null;
            /** Recording Mbid */
            recording_mbid?: string | null;
            /** Cover Art Url */
            cover_art_url?: string | null;
            /**
             * Has Listen Correction
             * @default false
             */
            has_listen_correction: boolean;
            /**
             * Has Track Correction
             * @default false
             */
            has_track_correction: boolean;
            /** Track Id */
            track_id?: number | null;
            /** Original Artist */
            original_artist?: string | null;
            /** Original Title */
            original_title?: string | null;
            /** Original Album */
            original_album?: string | null;
            /** Original Duration Secs */
            original_duration_secs?: number | null;
            /** Original Recording Mbid */
            original_recording_mbid?: string | null;
            /** Track Play Count */
            track_play_count?: number | null;
        };
        /** MBRecordingResult */
        MBRecordingResult: {
            /** Mbid */
            mbid: string;
            /** Title */
            title: string;
            /** Artist Credit */
            artist_credit: string;
            /** Release */
            release?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Length Ms */
            length_ms?: number | null;
            /** Release Mbid */
            release_mbid?: string | null;
        };
        /** MBSearchResponse */
        MBSearchResponse: {
            /** Results */
            results: components["schemas"]["MBRecordingResult"][];
        };
        /** MonthlyTrendInfo */
        MonthlyTrendInfo: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /** NarrativeResponse */
        NarrativeResponse: {
            /** Plain */
            plain: {
                [key: string]: string;
            };
            /** Rich */
            rich: {
                [key: string]: string;
            };
        };
        /** OnRepeatPeak */
        OnRepeatPeak: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** OnThisDayGroup */
        OnThisDayGroup: {
            /** Year */
            year: number;
            /** Listens */
            listens: components["schemas"]["ListenEntry"][];
        };
        /** OnThisDayResponse */
        OnThisDayResponse: {
            /** Groups */
            groups: components["schemas"]["OnThisDayGroup"][];
            /** Anniversaries */
            anniversaries: components["schemas"]["ArtistAnniversary"][];
        };
        /** PlayingNowResponse */
        PlayingNowResponse: {
            /** Is Playing */
            is_playing: boolean;
            /** Artist */
            artist?: string | null;
            /** Title */
            title?: string | null;
            /** Release */
            release?: string | null;
            /** Cover Art Url */
            cover_art_url?: string | null;
            last_played?: components["schemas"]["LastPlayedEntry"] | null;
        };
        /** StatsSummaryResponse */
        StatsSummaryResponse: {
            /** Total Listens */
            total_listens: number;
            /** Unique Artists */
            unique_artists: number;
            /** Unique Tracks */
            unique_tracks: number;
            /** Days Active */
            days_active: number;
            /** Avg Per Day */
            avg_per_day: number;
            /** Top Source */
            top_source: string;
            /** Db Type */
            db_type?: string | null;
            /** First Year */
            first_year?: number | null;
        };
        /** StreakStatsResponse */
        StreakStatsResponse: {
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
        };
        /** SyncStartResponse */
        SyncStartResponse: {
            /** Status */
            status: string;
            /** Mode */
            mode?: string | null;
            /** Message */
            message?: string | null;
        };
        /** SyncStatusResponse */
        SyncStatusResponse: {
            /** Running */
            running: boolean;
            /** Finished */
            finished: boolean;
            /** Mode */
            mode: string;
            /** Batches Fetched */
            batches_fetched: number;
            /** Synced Count */
            synced_count: number;
            /** Updated Count */
            updated_count: number;
            /** Deleted Count */
            deleted_count: number;
            /** Lb Total */
            lb_total: number;
            /** Local Total */
            local_total: number;
            /** Error */
            error?: string | null;
        };
        /** TopArtistTrendsResponse */
        TopArtistTrendsResponse: {
            /** Year */
            year: number;
            /** Trends */
            trends: components["schemas"]["ArtistTrendSeries"][];
        };
        /** TopArtistsResponse */
        TopArtistsResponse: {
            /** Items */
            items: components["schemas"]["ArtistInfo"][];
            /** Total Count */
            total_count: number;
        };
        /** TopTracksResponse */
        TopTracksResponse: {
            /** Items */
            items: components["schemas"]["TrackInfo"][];
            /** Total Count */
            total_count: number;
        };
        /** TrackBatchRequestItem */
        TrackBatchRequestItem: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
        };
        /** TrackBatchResponseItem */
        TrackBatchResponseItem: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Play Count */
            play_count: number;
            /** Duration Secs */
            duration_secs?: number | null;
        };
        /** TrackCorrectionRequest */
        TrackCorrectionRequest: {
            /** Track Id */
            track_id?: number | null;
            /** Corrected Artist */
            corrected_artist?: string | null;
            /** Corrected Title */
            corrected_title?: string | null;
            /** Corrections */
            corrections: {
                [key: string]: string | number | null;
            };
        };
        /** TrackInfo */
        TrackInfo: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Play Count */
            play_count: number;
            /** Rank */
            rank?: number | null;
        };
        /** TrackMonthlyTrend */
        TrackMonthlyTrend: {
            /** Month */
            month: string;
            /** Count */
            count: number;
        };
        /** TrackRevertRequest */
        TrackRevertRequest: {
            /** Track Id */
            track_id?: number | null;
            /** Corrected Artist */
            corrected_artist?: string | null;
            /** Corrected Title */
            corrected_title?: string | null;
        };
        /** TrackStatsResponse */
        TrackStatsResponse: {
            /** Play Count */
            play_count: number;
            /** Duration Secs */
            duration_secs?: number | null;
        };
        /** TrackTrendSeries */
        TrackTrendSeries: {
            /** Track */
            track: string;
            /** Play Count */
            play_count: number;
            /** Monthly Counts */
            monthly_counts: components["schemas"]["TrackMonthlyTrend"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyBreakdownItem */
        WeeklyBreakdownItem: {
            /** Week */
            week: number;
            /** Count */
            count: number;
        };
        /** WrappedArtist */
        WrappedArtist: {
            /** Name */
            name: string;
            /** Plays */
            plays: number;
        };
        /** WrappedDataResponse */
        WrappedDataResponse: {
            /** Total Plays */
            total_plays: number;
            top_artist?: components["schemas"]["WrappedArtist"] | null;
            top_track?: components["schemas"]["WrappedTrack"] | null;
            peak_day?: components["schemas"]["WrappedPeakDay"] | null;
            /** Minutes Listened */
            minutes_listened: number;
            on_repeat_peak?: components["schemas"]["OnRepeatPeak"] | null;
        };
        /** WrappedPeakDay */
        WrappedPeakDay: {
            /** Date */
            date: string;
            /** Plays */
            plays: number;
        };
        /** WrappedTrack */
        WrappedTrack: {
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Plays */
            plays: number;
        };
        /** _CoverArtItem */
        _CoverArtItem: {
            /** Id */
            id: number;
            /** Artist */
            artist: string;
            /** Title */
            title: string;
            /** Recording Mbid */
            recording_mbid?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSummaryResponse"];
                };
            };
        };
    };
    read_top_artists_api_top_artists_get: {
        parameters: {
            query?: {
                /** @description Time range in days: 30, 90, 365, or 'all' */
                range?: "30" | "90" | "365" | "all";
                /** @description Max results to return */
                limit?: number;
                /** @description Filter by artist name (case-insensitive substring) */
                search?: string | null;
                /** @description Page number */
                page?: number;
                /** @description Page size (overrides limit if set) */
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopArtistsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_top_tracks_api_top_tracks_get: {
        parameters: {
            query?: {
                /** @description Time range in days: 30, 90, 365, or 'all' */
                range?: "30" | "90" | "365" | "all";
                /** @description Max results to return */
                limit?: number;
                /** @description Filter by track or artist name (case-insensitive substring) */
                search?: string | null;
                /** @description Page number */
                page?: number;
                /** @description Page size (overrides limit if set) */
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopTracksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_heatmap_api_heatmap_get: {
        parameters: {
            query?: {
                /** @description The calendar year to display */
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_hourly_trends_api_trends_hourly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    read_punchcard_api_trends_punchcard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    read_monthly_trends_api_trends_monthly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyTrendInfo"][];
                };
            };
        };
    };
    read_streak_api_trends_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakStatsResponse"];
                };
            };
        };
    };
    read_narrative_api_narrative_get: {
        parameters: {
            query?: {
                /** @description Optional seed for daily stable randomization */
                seed?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_wrapped_api_wrapped_get: {
        parameters: {
            query?: {
                /** @description Filter by year (e.g. 2025) */
                year?: number | null;
                /** @description Filter by quarter: Q1, Q2, Q3, Q4 */
                quarter?: ("Q1" | "Q2" | "Q3" | "Q4") | null;
                /** @description Filter by month: M1 to M12 */
                month?: ("M1" | "M2" | "M3" | "M4" | "M5" | "M6" | "M7" | "M8" | "M9" | "M10" | "M11" | "M12") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WrappedDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_recent_api_recent_get: {
        parameters: {
            query?: {
                /** @description Max results per page (1–100) */
                limit?: number;
                /** @description Cursor: unix_ts of the last item from the previous page */
                before_ts?: number | null;
                /** @description Cursor: id of the last item from the previous page */
                before_id?: number | null;
                /** @description Anchor date: seek to first listen on or before YYYY-MM-DD */
                anchor_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_track_stats_api_track_stats_get: {
        parameters: {
            query: {
                /** @description Artist name */
                artist: string;
                /** @description Track title */
                title: string;
                /** @description Optional album name to scope the count */
                album?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_track_stats_batch_api_track_stats_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackBatchRequestItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackBatchResponseItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cover_art_api_cover_art_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_CoverArtItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playing_now_api_playing_now_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayingNowResponse"];
                };
            };
        };
    };
    get_last_played_api_last_played_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayingNowResponse"];
                };
            };
        };
    };
    start_sync_api_sync_post: {
        parameters: {
            query?: {
                /** @description Sync mode. 'normal': fast two-pass additive sync — pulls new scrobbles since last sync, then backfills any gaps. Safe to run daily. 'mirror': fetches your complete ListenBrainz history, inserts any missing rows, and deletes any local rows not on LB. Treats LB as the authoritative source of truth. Takes ~15 minutes for large histories. */
                mode?: "normal" | "mirror";
            };
            header?: {
                "x-sync-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusResponse"];
                };
            };
        };
    };
    read_on_this_day_api_on_this_day_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnThisDayResponse"];
                };
            };
        };
    };
    export_listens_api_export_get: {
        parameters: {
            query?: {
                format?: "csv" | "json";
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_day_listens_api_day__date_str__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calendar date (YYYY-MM-DD) in local timezone */
                date_str: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_monthly_weekly_breakdown_api_trends_monthly__year___month__weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
                month: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyBreakdownItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_top_artist_trends_api_top_artist_trends_get: {
        parameters: {
            query: {
                /** @description The calendar year to display */
                year: number;
                /** @description Max artists to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopArtistTrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_artist_trend_api_artist_trend_get: {
        parameters: {
            query: {
                /** @description Artist name */
                artist: string;
                /** @description The calendar year to display */
                year: number;
                /** @description Max tracks to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistTrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_artist_stats_api_artist_stats_get: {
        parameters: {
            query: {
                /** @description Artist name */
                name: string;
                range?: "30" | "90" | "365" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listen_api_listens__listen_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the listen */
                listen_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_listen_api_listens__listen_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the listen to delete */
                listen_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_listen_api_listens__listen_id__correction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the listen to correct */
                listen_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListenCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_listen_correction_api_listens__listen_id__correction_revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the listen to revert */
                listen_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_track_api_tracks_correction_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_track_correction_api_tracks_correction_revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackRevertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListenEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_musicbrainz_api_mb_search_get: {
        parameters: {
            query: {
                /** @description Artist name */
                artist: string;
                /** @description Track title */
                title: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MBSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_cover_art_api_cover_art_search_get: {
        parameters: {
            query: {
                /** @description Artist name */
                artist: string;
                /** @description Album / release title */
                album?: string;
                /** @description Recording MBID (if known, used for precise release lookup) */
                recording_mbid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverArtSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    playing_now_stream_api_playing_now_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    handle_http_get_api_graphql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The GraphiQL integrated development environment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not found if GraphiQL or query via GET are not enabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    handle_http_post_api_graphql_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
